print('MAD LIBS CODE TEST 1')
n1 = input('Enter a first nown: ')
n2 = input('Enter a second nown: ')
n3 = input('Enter a third nown: ')
adj1 = input('Enter a first adjective: ')
adj2 = input('Enter a second adjective: ')
ptv1 = input('Enter a verb in the past tense: ')
adv1 = input('Enter an adverb: ')
print('Today I went to the zoo. I saw a(n) ', adj1, ' ', n1, ' jumping up and down in its tree. He ', ptv1, ' ', adv1, ' through the large tunnel that led to its ', adj2, ' ', n2, '.  I got some peanuts and passed them through the cage to a gigantic gray ', n3, ' towering above my head.')
print('Credit: https://www.it.iitb.ac.in/~vijaya/ssrvm/worksheetscd/getWorksheets.com/Language%20Arts/madlibsdoc.pdf')